version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passer
      #POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: objective_shannon
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "6081:80"
